#!/bin/sh
#
# Proxy + WPAD/PAC bootstrap for WirelessAndroidAutoDongle.
#
# Invoked (backgrounded) from /boot/aawgd.conf, which /etc/init.d/rcS sources as
# root before any S??* init script runs. Because of that ordering, wlan0 has no
# address and dnsmasq is not running yet when we are first called -- so almost
# everything here happens after a wait loop.
#
# Everything lives on /persist (the only writable disk; / and /boot are ro).
#
set -u

PROXY_DIR=/persist/proxy
LOG=/persist/proxy/bootstrap.log

# Config, with defaults. Overridden by exported AAWG_EXTRA_* vars from
# /boot/aawgd.conf (rcS sources it under `set -o allexport`).
LISTEN_IP="${AAWG_EXTRA_PROXY_LISTEN_IP:-10.0.0.1}"
LISTEN_PORT="${AAWG_EXTRA_PROXY_PORT:-8080}"
UPSTREAM_IP="${AAWG_EXTRA_UPSTREAM_IP:-10.0.0.2}"
UPSTREAM_PORT="${AAWG_EXTRA_UPSTREAM_PORT:-8080}"
PAC_PORT="${AAWG_EXTRA_PAC_PORT:-80}"
PHONE_MAC="${AAWG_EXTRA_PHONE_MAC:-}"
# Which proxy the PAC hands out: "phone" (default) sends clients straight to the
# phone so it sees real client IPs; "dongle" routes them through tinyproxy.
PAC_TARGET="${AAWG_EXTRA_PAC_TARGET:-phone}"
SHUTDOWN_PORT="${AAWG_EXTRA_SHUTDOWN_PORT:-8081}"
# Empty means no token required. See the note in /boot/aawgd.conf.
SHUTDOWN_TOKEN="${AAWG_EXTRA_SHUTDOWN_TOKEN:-}"
# How often the dongle asks the app whether it should power off. 0 disables.
POLL_INTERVAL="${AAWG_EXTRA_SHUTDOWN_POLL:-15}"
WAIT_SECS="${AAWG_EXTRA_PROXY_WAIT:-60}"

log() { echo "[proxy-bootstrap $(date '+%H:%M:%S')] $*" >> "$LOG" 2>&1; }

# ---------------------------------------------------------------- stage 1
# Runs synchronously in the rcS shell, BEFORE S80dnsmasq starts dnsmasq.
# We bind-mount our dnsmasq.conf over the read-only one so dnsmasq picks up the
# WPAD options on its normal, first start -- no kill/restart race.
stage_early() {
	: > "$LOG"
	log "early stage: listen=${LISTEN_IP}:${LISTEN_PORT} upstream=${UPSTREAM_IP}:${UPSTREAM_PORT}"

	render_dnsmasq_conf "$PROXY_DIR/dnsmasq.conf.generated"

	if mount -o bind "$PROXY_DIR/dnsmasq.conf.generated" /etc/dnsmasq.conf 2>>"$LOG"; then
		log "bind-mounted generated dnsmasq.conf over /etc/dnsmasq.conf"
		echo bind > "$PROXY_DIR/.dnsmasq-method"
	else
		log "bind mount FAILED; will fall back to restarting dnsmasq in late stage"
		echo restart > "$PROXY_DIR/.dnsmasq-method"
	fi
}

# ---------------------------------------------------------------- stage 2
# Backgrounded. Waits for the AP to come up, then starts tinyproxy + the PAC
# web server, then watchdogs dnsmasq so a bad config can never leave the car
# without DHCP.
stage_late() {
	i=0
	while [ "$i" -lt "$WAIT_SECS" ]; do
		if ip -4 addr show wlan0 2>/dev/null | grep -q "inet ${LISTEN_IP}/"; then
			log "wlan0 has ${LISTEN_IP} after ${i}s"
			break
		fi
		i=$((i + 1))
		sleep 1
	done

	if ! ip -4 addr show wlan0 2>/dev/null | grep -q "inet ${LISTEN_IP}/"; then
		log "ERROR: wlan0 never got ${LISTEN_IP} within ${WAIT_SECS}s; giving up"
		dnsmasq_watchdog
		return 1
	fi

	start_tinyproxy
	start_pac_server
	start_shutdownd
	dnsmasq_watchdog
	log "bootstrap complete"
}

# ---------------------------------------------------------------- dnsmasq
render_dnsmasq_conf() {
	out="$1"
	pin=""
	[ -n "$PHONE_MAC" ] && pin="dhcp-host=${PHONE_MAC},${UPSTREAM_IP}"

	cat > "$out" <<EOF
# Generated by /persist/proxy/bootstrap.sh -- do not edit, edit bootstrap.sh.
# Stock upstream settings:
interface=wlan0
dhcp-range=10.0.0.2,10.0.0.20,12h
dhcp-authoritative

domain-needed
bogus-priv

# ---- proxy auto-configuration ----
domain=lan
dhcp-option=15,lan

# WPAD via DHCP option 252. Honoured by Windows, macOS, iOS and most desktop
# Linux. Android has never implemented it -- Android clients must have the PAC
# URL typed once, per-SSID, under Wi-Fi > Advanced > Proxy > Auto-config.
dhcp-option=252,"http://${LISTEN_IP}:${PAC_PORT}/wpad.dat"

# WPAD via DNS, for clients that probe http://wpad.<domain>/wpad.dat instead.
address=/wpad/${LISTEN_IP}
address=/wpad.lan/${LISTEN_IP}

# Deliberately advertise NO default gateway: this network has no route to the
# internet, everything must go through the proxy. It also keeps clients (the
# phone included) from installing a black-holed default route over Wi-Fi, which
# helps the phone keep cellular as its default path.
dhcp-option=3

${pin}
EOF
	log "rendered $out"
}

dnsmasq_watchdog() {
	# If our config stopped dnsmasq from coming up, revert and restart with the
	# stock one. Losing DHCP on the AP means the phone cannot associate, which
	# means no Android Auto -- never acceptable as a failure mode.
	i=0
	while [ "$i" -lt 30 ]; do
		pidof dnsmasq >/dev/null 2>&1 && { log "dnsmasq is running"; return 0; }
		i=$((i + 1))
		sleep 1
	done

	log "ERROR: dnsmasq not running after 30s -- reverting to stock config"
	umount /etc/dnsmasq.conf 2>>"$LOG"
	/etc/init.d/S80dnsmasq restart >>"$LOG" 2>&1 || dnsmasq >>"$LOG" 2>&1
	pidof dnsmasq >/dev/null 2>&1 \
		&& log "recovered: dnsmasq running on stock config" \
		|| log "FATAL: dnsmasq still down"
}

# ---------------------------------------------------------------- tinyproxy
start_tinyproxy() {
	bin="$PROXY_DIR/bin/tinyproxy"
	if [ ! -x "$bin" ]; then
		log "ERROR: $bin missing or not executable -- run install.sh from the Mac"
		return 1
	fi

	mkdir -p /persist/proxy/run
	sed -e "s|@LISTEN_IP@|${LISTEN_IP}|g" \
	    -e "s|@LISTEN_PORT@|${LISTEN_PORT}|g" \
	    -e "s|@UPSTREAM_IP@|${UPSTREAM_IP}|g" \
	    -e "s|@UPSTREAM_PORT@|${UPSTREAM_PORT}|g" \
	    "$PROXY_DIR/tinyproxy.conf.in" > "$PROXY_DIR/tinyproxy.conf"

	"$bin" -c "$PROXY_DIR/tinyproxy.conf" >>"$LOG" 2>&1
	sleep 1
	if pidof tinyproxy >/dev/null 2>&1; then
		log "tinyproxy listening on ${LISTEN_IP}:${LISTEN_PORT}, upstream ${UPSTREAM_IP}:${UPSTREAM_PORT}"
	else
		log "ERROR: tinyproxy failed to start; see $PROXY_DIR/tinyproxy.log"
	fi
}

# ---------------------------------------------------------------- PAC server
start_pac_server() {
	if [ "$PAC_TARGET" = "dongle" ]; then
		pac_ip="$LISTEN_IP"; pac_port="$LISTEN_PORT"
	else
		pac_ip="$UPSTREAM_IP"; pac_port="$UPSTREAM_PORT"
	fi
	log "PAC hands out PROXY ${pac_ip}:${pac_port} (target=${PAC_TARGET})"
	sed -e "s|@LISTEN_IP@|${LISTEN_IP}|g" \
	    -e "s|@LISTEN_PORT@|${LISTEN_PORT}|g" \
	    -e "s|@PROXY_IP@|${pac_ip}|g" \
	    -e "s|@PROXY_PORT@|${pac_port}|g" \
	    "$PROXY_DIR/www/wpad.dat.in" > "$PROXY_DIR/www/wpad.dat"
	# Same file under the other two names clients commonly ask for.
	cp -f "$PROXY_DIR/www/wpad.dat" "$PROXY_DIR/www/proxy.pac"
	cp -f "$PROXY_DIR/www/wpad.dat" "$PROXY_DIR/www/wpad.da"

	if busybox httpd -p "${LISTEN_IP}:${PAC_PORT}" -h "$PROXY_DIR/www" \
	     -c "$PROXY_DIR/www/httpd.conf" >>"$LOG" 2>&1; then
		log "busybox httpd serving PAC on ${LISTEN_IP}:${PAC_PORT}"
	elif [ -x "$PROXY_DIR/bin/pacd" ]; then
		log "busybox httpd unavailable, falling back to bundled pacd"
		"$PROXY_DIR/bin/pacd" "$LISTEN_IP" "$PAC_PORT" "$PROXY_DIR/www/wpad.dat" >>"$LOG" 2>&1 &
	else
		log "ERROR: no way to serve the PAC file (no busybox httpd, no pacd)"
	fi
}

start_shutdownd() {
	# Lets the phone app power the dongle down cleanly instead of the SD card
	# being yanked mid-write when car power drops.
	if [ ! -x "$PROXY_DIR/bin/shutdownd" ]; then
		log "shutdownd binary missing, skipping"
		return
	fi
	if [ "$POLL_INTERVAL" -gt 0 ] 2>/dev/null; then
		"$PROXY_DIR/bin/shutdownd" "$LISTEN_IP" "$SHUTDOWN_PORT" "$SHUTDOWN_TOKEN" \
			"$UPSTREAM_IP" "$UPSTREAM_PORT" "$POLL_INTERVAL" >>"$LOG" 2>&1
	else
		"$PROXY_DIR/bin/shutdownd" "$LISTEN_IP" "$SHUTDOWN_PORT" "$SHUTDOWN_TOKEN" >>"$LOG" 2>&1
	fi
	sleep 1
	if pidof shutdownd >/dev/null 2>&1; then
		[ "$POLL_INTERVAL" -gt 0 ] 2>/dev/null && \
			log "polling ${UPSTREAM_IP}:${UPSTREAM_PORT}/__aawg/poll every ${POLL_INTERVAL}s"
		if [ -n "$SHUTDOWN_TOKEN" ]; then
			log "shutdownd listening on ${LISTEN_IP}:${SHUTDOWN_PORT} (token required)"
		else
			log "shutdownd listening on ${LISTEN_IP}:${SHUTDOWN_PORT} (no token)"
		fi
	else
		log "ERROR: shutdownd failed to start"
	fi
}

# ---------------------------------------------------------------- entrypoint
case "${1:-}" in
	early) stage_early ;;
	late)  stage_late ;;
	start) stage_early; stage_late ;;
	*) echo "usage: $0 {early|late|start}" >&2; exit 1 ;;
esac
